---
title: "&"
output: 
  html_document:
    toc: FALSE
---
##### <strong>  Matt Mulè || [orcid](https://orcid.org/0000-0001-8457-2716) || [google scholar](https://scholar.google.com/citations?user=eDbDGyIAAAAJ&hl=en) || [github](https://github.com/MattPM)  </strong> 

I am a MD-PhD student in the NIH Oxcam program currently working at the NIH intramural research campus under the mentorship of [John Tsang (NIAID)](https://www.niaid.nih.gov/research/john-tsang-phd). My PhD work in collaboration with [Ken Smith (Cambridge)](http://www.med.cam.ac.uk/smith/) focuses on linking human immune system variations meaningful clinical phenotypes in cancer, vaccination, and autoimmune diseases.  
  
Much of my current work focuses on statistical modeling high throughput immune system measurements, for example, transcriptome, proteome and single cell multi-omics data generated from human clinical cohorts. I'm use statistical models (mixed models and "machine learning") to integrate information across biological scales as a means to understand the circuitry of immune system states. For example, how are robustly defined cell phenotypes correlated acros individuals with distinct clinical outcomes? Defining these global phenotypes help us understand how components of the immune system are linke to each other and how they are linked to outcomes. This knowledge can then inform biomarker development and therapeutic strategies. 
  
